export const COLOR_NAMES = [
  "canvas",
  "surface",
  "surface-muted",
  "border",
  "ink",
  "ink-muted",
  "accent",
  "accent-ink",
  "accent-soft",
  "warning",
  "warning-soft",
  "danger",
  "danger-ink",
  "success",
  "status-wishlist",
  "status-wishlist-soft",
  "status-applied",
  "status-applied-soft",
  "status-screening",
  "status-screening-soft",
  "status-interviewing",
  "status-interviewing-soft",
  "status-offer",
  "status-offer-soft",
  "status-rejected",
  "status-rejected-soft",
  "status-closed",
  "status-closed-soft",
] as const;

export type ColorName = (typeof COLOR_NAMES)[number];
export type ColorScheme = "light" | "dark";

export const COLORS: Readonly<Record<ColorScheme, Readonly<Record<ColorName, string>>>> = {
  light: {
    canvas: "#f6f8fc",
    surface: "#ffffff",
    "surface-muted": "#f3f4f6",
    border: "#e0e3ea",
    ink: "#111828",
    "ink-muted": "#4a5565",
    accent: "#4f39f6",
    "accent-ink": "#ffffff",
    "accent-soft": "#e8eeff",
    warning: "#963b00",
    "warning-soft": "#fef2c6",
    danger: "#c1000c",
    "danger-ink": "#ffffff",
    success: "#008235",
    "status-wishlist": "#55647a",
    "status-wishlist-soft": "#eaf1fa",
    "status-applied": "#0b5ed0",
    "status-applied-soft": "#e1f0ff",
    "status-screening": "#007187",
    "status-screening-soft": "#d5f5fc",
    "status-interviewing": "#7235d0",
    "status-interviewing-soft": "#f2eaff",
    "status-offer": "#007840",
    "status-offer-soft": "#d5f9e0",
    "status-rejected": "#bc1f4f",
    "status-rejected-soft": "#ffe7ea",
    "status-closed": "#606369",
    "status-closed-soft": "#edeef1",
  },
  dark: {
    canvas: "#030712",
    surface: "#0e172b",
    "surface-muted": "#182438",
    border: "#2c3b51",
    ink: "#f1f5f9",
    "ink-muted": "#a0afc4",
    accent: "#8b99ff",
    "accent-ink": "#030712",
    "accent-soft": "#201e50",
    warning: "#ffc21b",
    "warning-soft": "#461901",
    danger: "#ff666a",
    "danger-ink": "#030712",
    success: "#00df73",
    "status-wishlist": "#aebfd8",
    "status-wishlist-soft": "#1f2938",
    "status-applied": "#82baff",
    "status-applied-soft": "#122a52",
    "status-screening": "#58d1e5",
    "status-screening-soft": "#00323e",
    "status-interviewing": "#c4a4fe",
    "status-interviewing-soft": "#321e51",
    "status-offer": "#61da92",
    "status-offer-soft": "#0c341e",
    "status-rejected": "#f693a3",
    "status-rejected-soft": "#4b1622",
    "status-closed": "#b4b8be",
    "status-closed-soft": "#26292e",
  },
};

export const BRAND = {
  primary: "#4f46e5",
  night: "#0b1020",
  success: "#34d399",
} as const;

export const cssVariables = (scheme: ColorScheme): Record<string, string> =>
  Object.fromEntries(
    COLOR_NAMES.map((name) => {
      const hex = COLORS[scheme][name];
      const channels = [1, 3, 5].map((start) => parseInt(hex.slice(start, start + 2), 16));
      return [`--color-${name}`, channels.join(" ")];
    }),
  );
